### ISSUE TITLE
Issiue About 

### ISSUE THREAD

**Issue by puqie** [gui-fkb/twitch-accounts#8]
C:\Users\User\Desktop\twitch-accounts-master\twitch-accounts-master>go run main.go
twitch-accounts by xBadApple -  https://github.com/xBadApple
Starting account creation...
How many accounts do you want to create?
1
Creating account 1 of 1
panic: runtime error: index out of range [0] with length 0

goroutine 20 [running]:
github.com/ox-y/GoGmailnator.(*Session).Init(0xc0000279b8, 0x30?)
        C:/Users/User/go/pkg/mod/github.com/ox-y/!go!gmailnator@v0.0.0-20221007105726-efc90fa60848/session.go:33 +0x265
main.getTrashMailSession()
        C:/Users/User/Desktop/twitch-accounts-master/twitch-accounts-master/main.go:593 +0x136
main.createNewAccount()
        C:/Users/User/Desktop/twitch-accounts-master/twitch-accounts-master/main.go:74 +0x7d
main.main.func1(0x0)
        C:/Users/User/Desktop/twitch-accounts-master/twitch-accounts-master/main.go:61 +0x11a
created by main.main in goroutine 1
        C:/Users/User/Desktop/twitch-accounts-master/twitch-accounts-master/main.go:53 +0x206
exit status 2

Why is this happening do you know that?

**Comment by gui-fkb** [comment]
Can you try again? I'm not receiving the same error here. But I'm suspecting that the error you are facing is proxy related, maybe you can try first without using any proxy for testing purposes, just change the Config.go file  and make the Proxy attribute empty.

![image](https://github.com/user-attachments/assets/5e73d1d4-d16a-49fd-a7a5-79581db111cd)

But if you want to use proxy, go for the following pattern: http://user:pass@ip:port

don't forget to use the http prefix

**Comment by puqie** [comment]
Microsoft Windows [Version 10.0.17763.3650]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Administrator\Desktop\twitch-accounts-master\twitch-accounts-master>go run main.go
twitch-accounts by xBadApple -  https://github.com/xBadApple
Starting account creation...
How many accounts do you want to create?
10
Creating account 1 of 10
Creating account 10 of 10
Creating account 4 of 10
Creating account 7 of 10
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
Session is alive.
Session is alive.
Session is alive.
Session is alive.
Email address is claytmp+8ankr@gmail.com.
Getting twitch cookies.
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
Email address is sisatmp+6sb09@gmail.com.
Getting twitch cookies.
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
Email address is m.ic.caaj.o.s.e@gmail.com.
Getting twitch cookies.
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
Email address is monherry9+0fedm@gmail.com.
Getting twitch cookies.
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
Getting kasada code
Getting kasada code
Getting kasada code
Getting kasada code
Getting local integrity token
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
Getting local integrity token
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
Getting local integrity token
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
IntegrityToken: v4.local.IGyQEcSmPLTGq0VrKwVYOTzDigBqgkfkbvdjwhk+487...
Creating account...
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
Parsed error response: {Breached:false Error:Oops! We encountered an unexpected error. Please try again. Errors:[Oops! We encountered an unexpected error. Please try again.] ErrorCode:5025}
Creating account 8 of 10
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
IntegrityToken: v4.local.cinSLFQYLOTED8Qy6NHgySfLUkGPDQgql2psgdJ+487...
Creating account...
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
IntegrityToken: v4.local.XvoM83vIgV9kqnT8K05PaaZqJJ7hkPuvNoN4lDJ+487...
Creating account...
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
Parsed error response: {Breached:false Error:Oops! We encountered an unexpected error. Please try again. Errors:[Oops! We encountered an unexpected error. Please try again.] ErrorCode:5025}
Creating account 9 of 10
Parsed error response: {Breached:false Error:Oops! We encountered an unexpected error. Please try again. Errors:[Oops! We encountered an unexpected error. Please try again.] ErrorCode:5025}
Creating account 5 of 10
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
Session is alive.
Session is alive.
Session is alive.
Email address is monherry9+cuihd@gmail.com.
Getting twitch cookies.
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
Getting kasada code
Email address is mageerauld+efnsu@gmail.com.
Getting twitch cookies.
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
Email address is daratmp+idmoe@gmail.com.
Getting twitch cookies.
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
Getting kasada code
Getting kasada code
Getting local integrity token
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
IntegrityToken: v4.local.MCm7qNqjBp0Vg_KzpYciEOWdxEhEPItx4X-Yw6O+313...
Creating account...
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
Parsed error response: {Breached:false Error:Oops! We encountered an unexpected error. Please try again. Errors:[Oops! We encountered an unexpected error. Please try again.] ErrorCode:5025}
Creating account 2 of 10
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
Session is alive.
Email address is kentkouh+h3weg@gmail.com.
Getting twitch cookies.
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
Getting kasada code
Getting local integrity token
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
Getting local integrity token
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
IntegrityToken: v4.local.fkpsXsjQhmRDamQFuLWf9iUCkMplon_GEFvt2NN+487...
Creating account...
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
Getting local integrity token
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
IntegrityToken: v4.local.RQtZeUC0TAQhPUattrxUs_T_iCE9f6wfQnKCkzF+487...
Creating account...
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
Parsed error response: {Breached:false Error:Oops! We encountered an unexpected error. Please try again. Errors:[Oops! We encountered an unexpected error. Please try again.] ErrorCode:5025}
Creating account 6 of 10
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
Parsed error response: {Breached:false Error:Oops! We encountered an unexpected error. Please try again. Errors:[Oops! We encountered an unexpected error. Please try again.] ErrorCode:5025}
Creating account 3 of 10
IntegrityToken: v4.local.Or54TButgS6xUWmgffDDBwVh_jyUiQjyJk9buPz+487...
Creating account...
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
Parsed error response: {Breached:false Error:Oops! We encountered an unexpected error. Please try again. Errors:[Oops! We encountered an unexpected error. Please try again.] ErrorCode:5025}
Session is alive.
Session is alive.
Getting local integrity token
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
Email address is lia.g.gei.2.9.o@gmail.com.
Getting twitch cookies.
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
Email address is gugtenterf+y4kt9@gmail.com.
Getting twitch cookies.
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
Getting kasada code
Getting kasada code
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
IntegrityToken: v4.local.PE6CU-W17HQh0WBrMn7lieXMWf_ZNfdthpkJ-9N+487...
Creating account...
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
Parsed error response: {Breached:false Error:Oops! We encountered an unexpected error. Please try again. Errors:[Oops! We encountered an unexpected error. Please try again.] ErrorCode:5025}
Getting local integrity token
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
Getting local integrity token
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
IntegrityToken: v4.local.j0j_ivzgIqg98wDK8wXwNQHvyJnX3818zcQO-Dx+487...
Creating account...
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
IntegrityToken: v4.local.3DLd13-FmXqzxbHnoUB7SrEv7xv6H6Kdn4B2CiK+487...
Creating account...
!! There is no proxy configuration found. The requests are going to be handled without any proxy !!
Parsed error response: {Breached:false Error:Oops! We encountered an unexpected error. Please try again. Errors:[Oops! We encountered an unexpected error. Please try again.] ErrorCode:5025}
Parsed error response: {Breached:false Error:Oops! We encountered an unexpected error. Please try again. Errors:[Oops! We encountered an unexpected error. Please try again.] ErrorCode:5025}
Finished accounts creation.

Only 1 account created...

**Comment by gui-fkb** [comment]
Hey, that means that it worked without proxy, but your IP got blocked right away. 

Now try it using proxies, but remember to follow this pattern: http://user:pass@ip:port

I don't know which proxy service you are using, but some proxy services (like oxylabs) block connections on twitch and other streaming platforms, so find a proxy that supports connections on Twitch, personally i recommend using ProxyLogic

During the testing phases, remember to create and test one account at a time to avoid unnecessarily spending of Salamoonder credits.

**Comment by gui-fkb** [comment]
Hey, do you have any updates? Were you able to get it working? I'm almost certain this issue is related to the proxy.

I also want to let you know that I’ve made some updates to the project regarding email verification. Please ensure your project is up to date with the latest changes before testing again.

Let me know if you need further assistance!

If you'd like, feel free to reach out to me on Discord: _guirerume.

**Comment by puqie** [comment]
I added you as a friend via discord, we can talk about problems.
